Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace SAVINAFILMS
{
    public partial class Film
    {
        public Film()
        {
            FilmArtist = new HashSet<FilmArtist>();
            FilmGenre = new HashSet<FilmGenre>();
        }
        
        
        public int FilmId { get; set; }
        [Required(ErrorMessage = "Потрібно заповнити поле")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Довжина значення від 2 до 50 символів")]
        [Display(Name = "Назва фільму")]
       
        public string Name { get; set; }
        [Required(ErrorMessage = "Потрібно заповнити поле")]
        [Range(1600, 2020  , ErrorMessage = "Введіть від 1600 до поточного")]
        [Display(Name = "Рік виходу")]
        public int Release { get; set; }
        [Required(ErrorMessage = "Потрібно заповнити поле")]
        [RegularExpression(@"^[1-9][0-9]+$", ErrorMessage = "Введіть число ")]
        [DataType(DataType.Currency)]
        [Display(Name = "Бюджет в $")]
        public string Budget { get; set; }

        [Display(Name = "Режисер")]
        public int DirectorId { get; set; }

        [Display(Name = "Країна")]
        public int CountryId { get; set; }

        [Display(Name = "Опис фільму")]
        public string Description { get; set; }

        [Display(Name = "Країна")]
        public virtual Country Country { get; set; }
        [Display(Name = "Режисер")]
        public virtual Director Director { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual ICollection<FilmArtist> FilmArtist { get; set; }
        public virtual ICollection<FilmGenre> FilmGenre { get; set; }
    }
}

Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SautinSoft.Document;
using SautinSoft.Document.Tables;
using SAVINAFILMS;

namespace SAVINAFILMS.Controllers
{
    public class GenresController : Controller
    {
        private readonly lab_films_picContext _context;
        public DocumentCore dc = new DocumentCore();
        public GenresController(lab_films_picContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genre.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var genres = await _context.Genre.FirstOrDefaultAsync(m => m.GenreId == id);
            if (genres == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "FilmGenres", new { id = genres.GenreId, name = genres.Name });
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {

            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {

                    using var stream = new FileStream(fileExcel.FileName, FileMode.Create);
                    await fileExcel.CopyToAsync(stream);
                    using XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled);
                    List<List<string>> Errors = new List<List<string>>();
                    foreach (IXLWorksheet worksheet in workBook.Worksheets)
                    {
                        List<string> ErrorsExcelFile = new List<string>();
                        Genre newgenre;
                        var g = (from genre in _context.Genre
                                 where genre.Name.Contains(worksheet.Name)
                                 select genre).ToList();


                        if (g.Count > 0)
                        {
                            newgenre = g[0];
                        }
                        else
                        {
                            newgenre = new Genre
                            {
                                Name = worksheet.Name,
                                Description = "Завантажено з Excel-файлу "
                            };

                            _context.Genre.Add(newgenre);

                        }
                        await _context.SaveChangesAsync();
                        foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
                        {

                            Film film = new Film();
                            FilmGenre filmGenre = new FilmGenre();
                            string name = row.Cell(1).Value.ToString();
                            if (name.Length > 50 || name.Length < 3)
                            {
                                string template = "Назва листа альбому:{0}. Рядок: {1}. {2}";
                                 string message = "Довжина назви фільму <3 або >50 символів.";
                                string ErrorMessage = string.Format(template, worksheet.Name, row, message);
                                ErrorsExcelFile.Add(ErrorMessage);
                                continue;
                            }
                            var f = (from flm in _context.Film where flm.Name.Contains(name) select flm).ToList();
                            if (f.Count() > 0)
                            {
                                film = f[0];
                                var fg = (from flm in _context.FilmGenre where (flm.FilmId == film.FilmId && flm.Genre.Name == newgenre.Name) select flm).ToList();
                                if (fg.Count == 0)
                                {
                                    filmGenre.Film = film;
                                    filmGenre.Genre = newgenre;
                                    _context.FilmGenre.Add(filmGenre);
                                }
                                await _context.SaveChangesAsync();
                            }
                            else
                            {
                                film.Name = row.Cell(1).Value.ToString();

                                if (row.Cell(6).Value.ToString().Length < 3 || Convert.ToInt32(row.Cell(6).Value) > DateTime.Now.Year || Convert.ToInt32(row.Cell(6).Value) < 1600)
                                {
                                    string template = "Назва листа альбому: {0}. " +
                                 "Рядок: {1}. " +
                                 "{2}";
                                    string message = "  Рік виходу фільму <1600 або > поточного року або поле незаповнено.";
                                    string ErrorMessage = string.Format(template, worksheet.Name, row, message);
                                    ErrorsExcelFile.Add(ErrorMessage);
                                    continue;
                                }
                                film.Release = Convert.ToInt32(row.Cell(6).Value);
                                var match1 = Regex.Match(row.Cell(10).Value.ToString(), @"^(0|[1-9]+[0-9]*)(\.[0-9]+( )?)?( млн| млрд)$");
                                if (!match1.Success || row.Cell(10).Value.ToString().Length<2 )
                                {
                                    string template = "Назва листа альбому:{0}. Рядок: {1}. {2}";
                                    string message = " Бюджет фільму-десятковий дріб у неправильному форматі або поле незаповнено.";
                                    string ErrorMessage = string.Format(template, worksheet.Name, row, message); 
                                    ErrorsExcelFile.Add(ErrorMessage);
                                    continue;
                                }
                                film.Budget = row.Cell(10).Value.ToString();
                                film.Description = row.Cell(11).Value.ToString();
                                filmGenre.Film = film;
                                filmGenre.Genre = newgenre;

                                string name1 = row.Cell(9).Value.ToString();
                                if (name1.Length > 50 || name1.Length < 3)
                                {
                                    string template = "Назва листа альбому:{0}. Рядок: {1}. {2}";
                                    string message = "Довжина назви країни <3 або >50 символів, або поле незаповнено";
                                    string ErrorMessage = string.Format(template, worksheet.Name, row, message); 
                                    ErrorsExcelFile.Add(ErrorMessage);
                                    continue;
                                }
                                Country country;
                                var a = (from aut in _context.Country
                                         where aut.Name.Contains(row.Cell(9).Value.ToString())
                                         select aut).ToList();
                                if (a.Count() > 0)
                                {
                                    country = a[0];
                                }
                                else
                                {
                                    country = new Country
                                    {
                                        Name = row.Cell(9).Value.ToString()
                                    };
                                    _context.Add(country);
                                }
                                film.Country = country;

                                string name2 = row.Cell(2).Value.ToString();
                                var match5= Regex.Match(row.Cell(2).Value.ToString(), @"^([A-Z][a-z]+)\ ([A-Z][a-z]+)(\ ?([A-Z][a-z]+)?)|([А-ЯІЇЄЩ][а-яіїщє]+)\ ([А-ЯІЇЄЩ][а-яіїщє]+)(\ ?([А-ЯІЇЄЩ][а-яіїщє]+)?)$");
                                if (!match5.Success|| name2.Length > 50 || name2.Length < 3)
                                {
                                    string template = "Назва листа альбому:{0}. Рядок: {1}. {2}";
                                    string message = "Довжина імені режисера <3 або >50 символів, поле незаповнено або неправильний формат ";
                                    string ErrorMessage = string.Format(template, worksheet.Name, row, message); 
                                    ErrorsExcelFile.Add(ErrorMessage);
                                    continue;
                                }
                                Director director;
                                var n = (from aut in _context.Director
                                         where aut.Name.Contains(row.Cell(2).Value.ToString())
                                         select aut).ToList();
                                if (n.Count() > 0)
                                {
                                    director = n[0];
                                }
                                else
                                {
                                    director = new Director();
                                    director.Name = row.Cell(2).Value.ToString();
                                    var match = Regex.Match(row.Cell(3).Value.ToString(), @"ч|ж");

Views/Films/Create.cshtml
@model SAVINAFILMS.Film

@{
    ViewData["Title"] = "Create";
}
<head>
    <style>
        body {
            background-image: url(https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/r8K5nG9Pxiyh9wvn6/videoblocks-abstract-geometric-background-with-moving-lines-dots-and-triangles-plexus-fantasy-abstract-technology-loop-animations_bufk3nibfw_thumbnail-full01.png);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
       
    </style>
</head>
<h1>Додати фільм</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Release" class="control-label"></label>
                <input asp-for="Release" class="form-control" />
                <span asp-validation-for="Release" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DirectorId" class="control-label"></label>
                @Html.ActionLink("~Додати режисера", "create_director", new { f_id = ViewBag.FilmId })
                <select asp-for="DirectorId" class="form-control" asp-items="ViewBag.DirectorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                @Html.ActionLink("~Додати країну","create_country",new { f_id = ViewBag.FilmId })
                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Films/Delete.cshtml
@model SAVINAFILMS.Film

@{
    ViewData["Title"] = "Delete";
}
    <head>
        <style>
            body {
                background-image: url(https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/r8K5nG9Pxiyh9wvn6/videoblocks-abstract-geometric-background-with-moving-lines-dots-and-triangles-plexus-fantasy-abstract-technology-loop-animations_bufk3nibfw_thumbnail-full01.png);
                background-repeat: no-repeat;
                background-attachment: fixed;
                background-size: cover;
            }
        </style>
    </head>
<h1>Видалити фільм</h1>

<h3>Ви впевнені?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Release)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Release)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Director.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Films/Details.cshtml
@model SAVINAFILMS.Film

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Release)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Release)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.FilmId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Films/Edit.cshtml
@model SAVINAFILMS.Film

@{
    ViewData["Title"] = "Edit";
}
    <head>
        <style>
            body {
                background-image: url(https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/r8K5nG9Pxiyh9wvn6/videoblocks-abstract-geometric-background-with-moving-lines-dots-and-triangles-plexus-fantasy-abstract-technology-loop-animations_bufk3nibfw_thumbnail-full01.png);
                background-repeat: no-repeat;
                background-attachment: fixed;
                background-size: cover;
            }
        </style>
    </head>
<h1>Редагувати</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Release" class="control-label"></label>
                <input asp-for="Release" class="form-control" />
                <span asp-validation-for="Release" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget" class="control-label"></label>
                <input asp-for="Budget" class="form-control" />
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DirectorId" class="control-label"></label>
                <select asp-for="DirectorId" class="form-control" asp-items="ViewBag.DirectorId"></select>
                <span asp-validation-for="DirectorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Повернутися</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Films/Index.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<SAVINAFILMS.Film>

@{
    ViewData["Title"] = "Index";
}

<head>
    <style>
        body {
            background-image: url(https://images.unsplash.com/photo-1485846234645-a62644f84728?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            border-bottom-color: coral;
        }

        table {
            background-color: rgba(0, 0, 0, 0.6);
        }

        .text-dasha {
            color: white;
        }

        .text-dasha-link {
            color: #581845;
            font-size: 22px;
        }

        .text-dasha-link-btn {
            color: #ff7070;
        }

        a {
            color: #fffda6
        }
    </style>
</head>

<h1 class="text-dasha">ФІЛЬМИ</h1>

@if (User.Identity.IsAuthenticated)
{
    var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
    var customUserClaim = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == "customType") : null;
    var customTypeValue = customUserClaim != null ? customUserClaim.Value : User.Identity.Name;
    var roleOfUser = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value : "User";
    @if (roleOfUser == "admin")
    {


        <div>
            <h3>Оберіть Excel-файл для заватаження</h3>
            @using (Html.BeginForm("Import", "Genres", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
            {
                <div>
                    Завантажте Excel-файл:
                    <input type="file" name="fileExcel" id="fileExcel" />
                    <div>
                        <input type="submit" value="Завантажити" />
                    </div>
                </div>
            }
        </div>
    }
}
<p>
    <a asp-action="Create" class="text-dasha-link">Додати новий фільм</a>
</p>

<table class="table">
    <thead>
        <tr class="text-dasha">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Release)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Budget)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="text-dasha">
                <td width="10%">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td width="5%">
                    @Html.DisplayFor(modelItem => item.Release)
                </td>
                <td width="5%">
                    @Html.DisplayFor(modelItem => item.Budget)
                </td>
                <td width="40%">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td width="10%" class="navbar-light">
                    @Html.DisplayFor(modelItem => item.Country.Name)
                </td>
                <td width="10%" class="navbar-light">
                    @Html.DisplayFor(modelItem => item.Director.Name)
                </td>
                <td width="20%">
                    @if (User.Identity.IsAuthenticated)
                    {
                        var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
                        var customUserClaim = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == "customType") : null;
                        var customTypeValue = customUserClaim != null ? customUserClaim.Value : User.Identity.Name;
                        var roleOfUser = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value : "User";
                        @if (roleOfUser == "admin")
                        {

                        }
                    }
                    <a asp-action="Edit" asp-route-id="@item.FilmId" class="text-dasha-link-btn">|Редагувати|</a>
                    <a asp-action="Delete" asp-route-id="@item.FilmId" class="text-dasha-link-btn">|Видалити|</a>
                    <a asp-action="Details" asp-route-id="@item.FilmId" class="text-dasha-link-btn">|Жанри фільму|</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{ var a = 1;
    <h1>a=@(a + 2)</h1>
}